/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteServiciiRouteImport } from './routes/_site.servicii'
import { Route as SitePortofoliuRouteImport } from './routes/_site.portofoliu'
import { Route as SiteContactRouteImport } from './routes/_site.contact'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServiciiRoute = SiteServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortofoliuRoute = SitePortofoliuRouteImport.update({
  id: '/portofoliu',
  path: '/portofoliu',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/contact': typeof SiteContactRoute
  '/portofoliu': typeof SitePortofoliuRoute
  '/servicii': typeof SiteServiciiRoute
}
export interface FileRoutesByTo {
  '/contact': typeof SiteContactRoute
  '/portofoliu': typeof SitePortofoliuRoute
  '/servicii': typeof SiteServiciiRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/portofoliu': typeof SitePortofoliuRoute
  '/_site/servicii': typeof SiteServiciiRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/portofoliu' | '/servicii'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/portofoliu' | '/servicii' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/contact'
    | '/_site/portofoliu'
    | '/_site/servicii'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/servicii': {
      id: '/_site/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof SiteServiciiRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portofoliu': {
      id: '/_site/portofoliu'
      path: '/portofoliu'
      fullPath: '/portofoliu'
      preLoaderRoute: typeof SitePortofoliuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SitePortofoliuRoute: typeof SitePortofoliuRoute
  SiteServiciiRoute: typeof SiteServiciiRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SitePortofoliuRoute: SitePortofoliuRoute,
  SiteServiciiRoute: SiteServiciiRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
